name: solid_auth
description: Authentication library to connect to a Solid server from solidproject.org
version: 0.2.0-dev.1
homepage: https://github.com/anusii/solid_auth

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.1
  convert: ^3.1.2
  crypto: ^3.0.6
  fast_rsa: ^3.8.1
  http: ^1.3.0
  logging: ^1.3.0
  # FIXME: why was pointycastle downgraded to ^3.9.1 before?
  pointycastle: '>=3.9.1 <5.0.0'
  uuid: ^4.5.1
  oidc: ^0.13.0
  oidc_default_store: ^0.5.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^6.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
  assets:
    - packages/fast_rsa/web/assets/worker.js
    - packages/fast_rsa/web/assets/wasm_exec.js
    - packages/fast_rsa/web/assets/rsa.wasm

